using ISysDomainBack.Units;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISysDomainBack.Company
{
    internal class Department
    {
        /// <summary>
        /// Autogenerated primary key in string format. Represents Guid
        /// </summary>
        [Required]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Name of department
        /// </summary>
        public string Title { get; set; } = String.Empty;

        /// <summary>
        /// Subdivision code
        /// </summary>
        public string SubdivisionCode { get; set; } = String.Empty;

        /// <summary>
        /// Department employees
        /// </summary>
        public ICollection<Employee>? Employees { get; set; } = new List<Employee>();
    }
}
