using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISysDomainBack.Projects
{
    internal class Project
    {
        /// <summary>
        /// Autogenerated primary key in string format. Represents Guid
        /// </summary>
        [Required]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Name of department
        /// </summary>
        public string Title { get; set; } = String.Empty;

        /// <summary>
        /// Project code
        /// </summary>
        public string ProjectCode { get; set; } = String.Empty;

        /// <summary>
        /// A field that implements a many-to-many relationship with the Employee class
        /// </summary>
        public ICollection<EmployeeProjects>? EmployeeProjects { get; set; } = new List<EmployeeProjects>();
    }
}
